#!/usr/bin/env bash

source "$HOME/.cache/wal/colors.sh"

cat > "$HOME/.config/hypr/colors.conf" <<EOF
# Auto-generated by pywal (Hyprland)

\$background = 0xff${background#\#}
\$foreground = 0xff${foreground#\#}

\$color0 = 0xff${color0#\#}
\$color1 = 0xff${color1#\#}
\$color2 = 0xff${color2#\#}
\$color3 = 0xff${color3#\#}
\$color4 = 0xff${color4#\#}
\$color5 = 0xff${color5#\#}
\$color6 = 0xff${color6#\#}
\$color7 = 0xff${color7#\#}
EOF
